services:
  - type: web
    name: voxwave-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: voxwave-db
          property: connectionString
      - key: ELEVENLABS_API_KEY
        sync: false # Set this manually in dashboard
      - key: ELEVENLABS_BASE_URL
        value: https://api.elevenlabs.io/v1
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: MAX_FILE_SIZE
        value: 26214400
      - key: AUDIO_CLEANUP_DAYS
        value: 7

databases:
  - name: voxwave-db
    plan: starter